/* Solution - 1 */

SELECT name FROM Employee order by name asc;

/* Solution - 2 */

SELECT * FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000;

/* Solution - 3 */

SELECT NAME FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;

/* Solution - 4 */

SELECT * FROM CITY;

/* Solution - 5 */

SELECT * FROM CITY WHERE ID = 1661;

/* Solution - 6 */

SELECT * FROM CITY WHERE COUNTRYCODE = 'JPN'; 


/* Solution - 7 */

SELECT NAME FROM CITY WHERE COUNTRYCODE='JPN';


/* Solution - 8 */

SELECT CITY,STATE FROM STATION;


/* Solution - 9 */

SELECT ROUND(SUM(LAT_N),2),ROUND(SUM(LONG_W),2) FROM STATION;


/* Solution - 10 */


SELECT DISTINCT CITY FROM STATION WHERE MOD(ID,2) = 0;


/* Solution - 11 */


SELECT COUNT(CITY)- COUNT(DISTINCT CITY) FROM STATION;



/* Solution - 12 */


SELECT City, LENGTH(City)
FROM (SELECT City
      FROM Station
     ORDER BY LENGTH(City), City)
WHERE ROWNUM = 1;
SELECT City, LENGTH(City)
FROM (SELECT City
      FROM Station
     ORDER BY LENGTH(City) DESC, City)
WHERE ROWNUM = 1;


/* Solution - 13 */

SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%';


/* Solution - 14 */


SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u';





